### ISSUE TITLE
[joss-review] Fix installation instructions in README

### ISSUE THREAD

**Issue by hgandhi2411** [IPESE/REHO#17]
README installation instructions direct the users to the "User guide" section of documentation for detailed instructions. However, these instructions are under "Getting Started". Please consolidate the differences between the github instructions and documentation. 
I would advise providing either complete installation steps in the README or directing users to the documentation page. The way it stands currently, the steps provided in README are incomplete.

**Comment by DorsanL** [comment]
Thank you for pointing this out, it has now been corrected!
https://github.com/IPESE/REHO/commit/2528ccbc279cf3e0028ef1561118901ed65e7637
