### ISSUE TITLE
[JOSS review] Tests

### ISSUE THREAD

**Issue by nmstreethran** [IPESE/REHO#22]
https://github.com/openjournals/joss-reviews/issues/6734

JOSS requires:

> Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

Do you have any tests implemented? I can't seem to find them.

**Comment by hgandhi2411** [comment]
@DorsanL unit tests are a best practice when creating packages and help detect if code is broken when changes are made. So, I would recommend that you add some tests.

**Comment by nmstreethran** [comment]
I agree that unit tests are needed. The tests don't need to be automated; manual steps to run them are fine. You can have a look at any recent JOSS papers for suggestions, e.g. [pyheatdemand](https://github.com/AlexanderJuestel/pyheatdemand).

**Comment by DorsanL** [comment]
Entry points for test have been added.
https://github.com/IPESE/REHO/commit/4a63b03aec4f85ae097582e4bd1ab2c3b5d03e0c

The "Checking proper installation" section of the documentation has been updated accordingly.
https://reho.readthedocs.io/en/main/sections/5_Getting_started.html#checking-proper-installation

**Comment by nmstreethran** [comment]
I still can't seem to find any tests to verify the functionality and methods in the package, e.g. assertion and exception testing. The tests you currently have only seem to check whether the imports work and if the scripts manage to execute. (Please correct me if I'm wrong.)

The pyheatdemand package I linked in my earlier comment has these tests for example: https://github.com/AlexanderJuestel/pyheatdemand/blob/main/test/test_processing.py.

**Comment by DorsanL** [comment]
I started implementing some functionality tests with pytest (https://github.com/IPESE/REHO/commit/fda9b0ef9b6ff29f01211cc0b6a6e6cb66a8eca9). This is only a draft, I will extend them in the coming days.

**Comment by DorsanL** [comment]
A folder `reho/test/` is now part of the package, containing the following files and functionality tests:

- _test_import.py_ verifies the import of the different **REHO** modules
- _test_clustering.py_ verifies the behavior of **Clustering** class
- _test_infrastructure.py_ verifies the behavior of **Infrastructure** class
- _test_run.py_ ensures that a classic optimisation works as intended (and thereby that the **SubProblem**, **MasterProblem** and **REHO** classes work properly)
- _test_plot.py_ (calls _test_run_ to generate results) and verifies various plotting functions
- _test_examples.py_ runs each of the examples available in `scripts/examples/` (and downloads them locally beforehand if they have not been cloned)

Developments have been pushed in https://github.com/IPESE/REHO/commit/254a8bc1476dc9250208d94b6446b4953017c783
