### ISSUE TITLE
[JOSS Review]: Use entry point for getting started

### ISSUE THREAD

**Issue by willu47** [IPESE/REHO#23]
### Summary

Instead of requiring users to manually download a folder of data and a script from the repository, develop a simple command-line interface and a `test` or `setup` [console script](https://packaging.python.org/en/latest/specifications/entry-points/) which automates this process.

### Detailed design

A command such as `$ reho setup` would download (or copy from the installed package) the required data and scripts to the current folder and then execute them.

**Comment by DorsanL** [comment]
Thank you for this suggestion. Entry points for test have been added.
https://github.com/IPESE/REHO/commit/4a63b03aec4f85ae097582e4bd1ab2c3b5d03e0c

The "Checking proper installation" section of the documentation has been updated accordingly.
https://reho.readthedocs.io/en/main/sections/5_Getting_started.html#checking-proper-installation

**Comment by DorsanL** [comment]
Entry points consist of:
```
reho-run-test
reho-plot-test
reho-examples-test
```
and allow to verify the proper installation of REHO and that all examples are running (https://github.com/IPESE/REHO/commit/3860931485cd3de224461d0d6f58c16d82d498af)
