### ISSUE TITLE
[JOSS Review]: Doc strings for some functions/package files missing in Package structure

### ISSUE THREAD

**Issue by hgandhi2411** [IPESE/REHO#26]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What happened?

Doc strings for many of the plotting functions appears as "TODO" or is completely missing in the [Package Structure](https://reho.readthedocs.io/en/main/sections/4_Package_structure.html) page. Corresponding functions are also missing doc strings in the code for these files `rainbow_plots.py, sankey.py and plotting.py ` 

### Version

1.0.2 (Stable)

### Anything else?

![image](https://github.com/IPESE/REHO/assets/22055417/f932b2e5-177c-4f83-af5a-eda64cb154a1)

**Comment by DorsanL** [comment]
The missing DocStrings have been added or completed, and the deprecated plotting functions removed.
https://github.com/IPESE/REHO/commit/c14cf7479d126da81a90bafaaa6b0754a5548aa6

Documentation for the plotting functions seems now fine.
https://reho.readthedocs.io/en/main/sections/4_Package_structure.html#module-reho.plotting
