### ISSUE TITLE
JOSS REVIEW: Paper

### ISSUE THREAD

**Issue by willu47** [IPESE/REHO#36]
I spotted a few typos in the [paper](https://github.com/openjournals/joss-papers/blob/joss.06734/joss.06734/10.21105.joss.06734.pdf):

- line 17 add "**The** documentation website"
- line 26 add "**The** intensification of..."

**Comment by DorsanL** [comment]
Thank you, it has been corrected (https://github.com/IPESE/REHO/commit/82b76a4f09038fc0a27d8d9ba4af41ad9c189edb)

The updated paper can be downloaded here: https://github.com/IPESE/REHO/actions/runs/11259187496/artifacts/2036040498
